#centos6.9sshd_lamp
FROM centos:6.9
RUN  yum install openssh-server htppd mysql mysql-server php php-mysql unzip -y
RUN /etc/init.d/sshd start && echo "root" | passwd  root --stdin  && /etc/init.d/mysqld start && /etc/init.d/httpd start
COPY init.sh /
ADD http://download.comsenz.com/DiscuzX/3.3/Discuz_X3.3_SC_UTF8.zip /var/www
RUN cd /var/www/ && unzip Discuz_X3.3_SC_UTF8.zip && cp -r upload/* html && chown -R apache.apache /var/www/html
EXPOSE 80
EXPOSE 22
EXPOSE 3306
CMD ["/bin/sh","/init.sh"]
